### ISSUE TITLE
Microsoft Sharepoint credential not working

### ISSUE THREAD

**Issue by schroedan** [Savjee/n8n-nodes-microsoft-sharepoint#1]
When I create a new "Microsoft Sharepoint account" and select "Connect my account", the error "OAuth Authorization Error" appears with the message "Invalid URL". If I create a generic "Microsoft account" (`microsoftOAuth2Api`) with the scope `openid offline_access User.ReadWrite.All Group.ReadWrite.All Chat.ReadWrite Sites.ReadWrite.All` instead, then the authorization popup from Microsoft appears. I can see the following error in the logs:
```
Invalid URL
TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at CodeFlow.getUri (/usr/local/lib/node_modules/n8n/node_modules/@n8n/client-oauth2/dist/CodeFlow.js:37:21)
    at OAuth2CredentialController.getAuthUri (/usr/local/lib/node_modules/n8n/dist/controllers/oauth/oauth2-credential.controller.js:85:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
    at /usr/local/lib/node_modules/n8n/dist/response-helper.js:105:26
```

I assume that the `properties` of the base credential are missing in the [credentials/MicrosoftSharepointOAuth2Api.credentials.ts](https://github.com/Savjee/n8n-nodes-microsoft-sharepoint/blob/master/credentials/MicrosoftSharepointOAuth2Api.credentials.ts) file?

**Comment by schroedan** [comment]
This was a configuration error. Instead of the `common` tenant, the corresponding ID for the auth/token URL had to be set here. A better error message would have been helpful here.

**Comment by e-yavuz-1** [comment]
Thank you, @schroedan, it helped much.

https://login.microsoftonline.com/{tenantID}/oauth2/v2.0/authorize
https://login.microsoftonline.com/{tenantID}/oauth2/v2.0/token

To get tenantID, please visit Azure Portal -> Your App -> Directory (tenant) ID

Hi @Savjee Please modify the code to correct it or mention it in the documentation.

**Comment by Savjee** [comment]
This node wraps around n8n's Microsoft Graph credentials. Not much I can do there. 

But I'm happy to accept pull requests to add documentation!
